org.gradle.jvmargs=-XX:MaxMetaspaceSize=4096m
org.gradle.parallel=true

kotlin.version=2.1.0
log4j.version=2.23.1
simpleyaml.version=1.8.4
jetbrains-annotations.version=24.1.0
commons-io.version=2.16.1
google-gson.version=2.11.0
json.version=20240303
zip4j.version=2.11.5
slf4j.version=2.0.13
xseries.version=13.0.0