name: "Build and Deploy [development]"
on:
  push:
    branches: [development]
jobs:
  build:
    name: "Build and Deploy [development]"
    if: ${{ github.ref != 'refs/heads/master' && !contains(github.event.head_commit.message, '[skip ci]') }}
    # Set up the OS
    runs-on: ubuntu-latest
    env:
      # Sonatype Credentials & GitHub token
      SONATYPE_USERNAME: '${{ secrets.SONATYPE_USERNAME }}'
      SONATYPE_PASSWORD: '${{ secrets.SONATYPE_PASSWORD }}'
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      PUBLIC_KEY: '${{ secrets.PUBLIC_KEY }}'
      SIGNING_KEY: '${{ secrets.SIGNING_KEY }}'
      SIGNING_PASSWORD: '${{ secrets.SIGNING_PASSWORD }}'
      # Set environment
      ENV: 'dev'
    steps:
      # Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v4
      # Set up git hashes environment variables
      - name: Git Hashes
        uses: Im-Fran/git-hashes-action@v1.0.3
      # Set up the JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      # Clean, Test, Publish and Build (in that order to save the artifact to the action)
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean test deploy
      # Now we store the artifacts in the action
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./build/libs/simplecoreapi-*.jar