#name: "Build and Deploy [development]"
#on:
#  push:
#    paths: [ 'simplecoreapi/**' ]
#jobs:
#  build:
#    name: "Build and Deploy [development]"
#    if: ${{ github.ref != 'refs/heads/master' && !contains(github.event.head_commit.message, '[skip ci]') }}
#    # Set up the OS
#    runs-on: ubuntu-latest
#    env:
#      # Sonatype Credentials & GitHub token
#      SONATYPE_USERNAME: '${{ secrets.SONATYPE_USERNAME }}'
#      SONATYPE_PASSWORD: '${{ secrets.SONATYPE_PASSWORD }}'
#      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
#      # Set environment
#      ENV: 'dev'
#    steps:
#      # Checkout the Code
#      - name: Checkout Code
#        uses: actions/checkout@v4
#      # Set up git hashes environment variables
#      - name: Git Hashes
#        uses: Im-Fran/git-hashes-action@v1.0.3
#      # Set up the JDK
#      - name: Set up JDK 11
#        uses: actions/setup-java@v4
#        with:
#          distribution: adopt
#          java-version: 11
#      # Clean, Test, Publish and Build (in that order to save the artifact to the action)
#      - name: Build with Gradle
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: clean test shadowJar dokkaHtml publish publishToSonatype closeAndReleaseSonatypeStagingRepository
#      # Now we store the artifact in the action
#      - name: Upload the artifact
#        uses: actions/upload-artifact@v5
#        with:
#          name: SimpleCoreAPI
#          path: ./simplecoreapi/build/libs/SimpleCoreAPI-${{ env.GIT_COMMIT_SHORT_HASH }}.jar
