name: "Build and Deploy [production]"
on:
  release:
    types: [published,edited]
jobs:
  build:
    name: "Build and Deploy [production]"
    # Set up the OS
    runs-on: ubuntu-latest
    env:
      # Sonatype Credentials & GitHub token
      SONATYPE_USERNAME: '${{ secrets.SONATYPE_USERNAME }}'
      SONATYPE_PASSWORD: '${{ secrets.SONATYPE_PASSWORD }}'
      PUBLIC_KEY: '${{ secrets.PUBLIC_KEY }}'
      SIGNING_KEY: '${{ secrets.SIGNING_KEY }}'
      SIGNING_PASSWORD: '${{ secrets.SIGNING_PASSWORD }}'
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      # Set environment
      ENV: 'prod'
    steps:
      # Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v4
      # Set up git hashes environment variables
      - name: Git Hashes
        uses: Im-Fran/git-hashes-action@v1.0.3
        # Set up version from tag environment variables
      - name: Version from Tag Action
        uses: Im-Fran/version-from-tag-action@v1.0.3
        with:
          remove-first-character: 'v'
        # Set up the JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      # Clean, Test, Publish and Build (in that order to save the artifact to the action)
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean test deploy
      # Now we store the artifacts in the action
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./build/libs/simplecoreapi-*.jar
      # Here we upload the binary to the release
      - uses: d1ceward/draft-assets-release-action@v2
        name: Upload to release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build/libs/simplecoreapi-bukkit.jar
            build/libs/simplecoreapi-paper.jar
            build/libs/simplecoreapi-bungee.jar
            build/libs/simplecoreapi-velocity.jar
      # Now we deploy the documents to GitHub pages
      - name: Deploy Dokka
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: build/dokka
          clean: true
          clean-exclude: |
            CNAME
