name: "Build and Deploy"
on:
  release:
    types: [published,edited]
jobs:
  build:
    # Set up the OS
    runs-on: ubuntu-latest
    env:
      # Nexus credentials and GitHub token
      NEXUS_USERNAME: '${{ secrets.NEXUS_USERNAME }}'
      NEXUS_PASSWORD: '${{ secrets.NEXUS_PASSWORD }}'
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      # Set environment
      env: 'prod'
      # Retrieve the version from 'github.ref_name' context and remove the first character 'v' if is present
      VERSION: '$(echo ${{ github.ref_name }} | sed -e "s/^v//")'
      # Save the short version of the commit hash
      GIT_FULL_HASH: '${{ github.sha }}'
      GIT_SHORT_HASH: '$(echo ${{ github.sha }} | cut -c1-7)'
    steps:
    # Checkout the Code
    - name: Checkout Code
      uses: actions/checkout@v2
    # Set up the JDK
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    # Make gradle executable
    - name: Make gradle executable
      run: chmod +x gradlew
    # Clean, Test, Publish and Build (in that order to save the artifact to the action)
    - name: Test, Deploy and Build with Gradle
      run: ./gradlew clean test publish shadow
    # Now we store the artifact in the action
    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
        name: SimpleCoreAPI
        path: ./build/libs/SimpleCoreAPI.jar
    # Now we deploy the documents to GitHub pages
    - name: Deploy Dokka
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: build/dokka
        clean: true