name: Java CI
on:
  release:
    types: [published]
jobs:
  build:
    # Setup the OS
    runs-on: ubuntu-latest
    env:
      NEXUS_USERNAME: '${{ secrets.NEXUS_USERNAME }}'
      NEXUS_PASSWORD: '${{ secrets.NEXUS_PASSWORD }}'
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      env: 'prod'
    steps:
    # Checkout the code
    - name: Ceckout the Code
      uses: actions/checkout@v2
    # Install java and maven
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    # Test and deploy
    - name: Make gradle executable
      run: chmod +x gradlew
    - name: Test and Deploy with Gradle
      run: ./gradlew clean test publish shadow
      # Now we store the artifact in the action
    - name: Create & Copy artifact
      run: mkdir -p ./artifacts && cp build/libs/SimpleCoreAPI.jar ./artifacts/
    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
        name: SimpleCoreAPI
        path: ./artifacts/SimpleCoreAPI.jar
     - name: Deploy Dokka
       uses: JamesIves/github-pages-deploy-action@4.1.7
       with:
         branch: gh-pages
         folder: build/dokka
         clean: true
      
      
